# Generated by Django 5.2.13 on 2026-04-21 01:54

from django.db import migrations

CREATE_FN = """
    CREATE TABLE IF NOT EXISTS public.keepalive (
        id        smallint PRIMARY KEY,
        last_ping timestamptz NOT NULL DEFAULT NOW()
    );
    INSERT INTO public.keepalive (id, last_ping) VALUES (1, NOW());

    CREATE OR REPLACE FUNCTION fn_prevent_pausing()
    RETURNS SMALLINT LANGUAGE plpgsql AS $$
    DECLARE
        v_count smallint;
    BEGIN
        UPDATE public.keepalive SET last_ping = NOW() WHERE id = 1;

        SELECT COUNT(*) INTO v_count
        FROM emr_medical_record
        WHERE last_modified BETWEEN
            (CURRENT_TIMESTAMP - INTERVAL '7 day') AND CURRENT_TIMESTAMP;

        RETURN v_count;
    END;
    $$;
"""

DROP_FN = """
    DROP FUNCTION IF EXISTS fn_prevent_pausing();
    DROP TABLE IF EXISTS public.keepalive;
"""


def forwards_func(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return
    schema_editor.execute(CREATE_FN)


def backwards_func(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return
    schema_editor.execute(DROP_FN)


class Migration(migrations.Migration):
    dependencies = []

    operations = [
        migrations.RunPython(forwards_func, backwards_func),
    ]
