# Generated by Django 5.2.13 on 2026-04-21 01:54

from django.db import migrations

CREATE_FN = """
    CREATE OR REPLACE FUNCTION fn_prevent_pausing()
    RETURNS SMALLINT LANGUAGE plpgsql AS $$
    BEGIN
        PERFORM pg_sleep_for('45 seconds');
        RETURN COUNT(*) FROM emr_medical_record
            WHERE last_modified BETWEEN
                (CURRENT_TIMESTAMP - INTERVAL '7 day') AND CURRENT_TIMESTAMP;
    END;
    $$;
"""

DROP_FN = "DROP FUNCTION IF EXISTS fn_prevent_pausing();"


def forwards_func(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return
    schema_editor.execute(CREATE_FN)


def backwards_func(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return
    schema_editor.execute(DROP_FN)


class Migration(migrations.Migration):
    dependencies = []

    operations = [
        migrations.RunPython(forwards_func, backwards_func),
    ]
