# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-17 01:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0003_auto_20170916_0147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalrecord',
            name='additional_notes',
            field=models.TextField(blank=True, verbose_name='Additional Notes'),
        ),
    ]
