# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-02 01:12
from __future__ import unicode_literals

from django.db import migrations, models

import emr.models


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0004_auto_20170917_0158'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='profile_picture',
            field=models.ImageField(blank=True, upload_to=emr.models.patient_profile_picture_path, verbose_name='Profile Picture'),
        ),
    ]
