# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-18 19:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0005_patient_profile_picture'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patient',
            options={'ordering': ['id'], 'verbose_name': 'Patient', 'verbose_name_plural': 'Patients'},
        ),
        migrations.AlterModelTable(
            name='medicalrecord',
            table='emr_medical_record',
        ),
    ]
