# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-01 01:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identification', models.CharField(max_length=9)),
                ('date_added', models.DateTimeField()),
                ('first_name', models.CharField(max_length=45)),
                ('last_name', models.CharField(max_length=45)),
                ('sex', models.IntegerField()),
                ('date_of_birth', models.DateField()),
                ('occupation', models.CharField(max_length=45)),
                ('phone_number', models.CharField(max_length=8)),
                ('address', models.TextField()),
            ],
        ),
    ]
